# Data Science Academy - Python Fundamentos - Capítulo 10

---

## Hello World

In [1]:
import tensorflow as tf

2022-03-27 15:57:18.236216: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-27 15:57:18.236362: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.8.0'

In [3]:
hello = tf.constant("Hello, TensorFlow!")
print(hello)

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


2022-03-27 15:57:33.929210: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-27 15:57:33.929496: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-27 15:57:33.929602: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (LAPTOP-B1P6J1UM): /proc/driver/nvidia/version does not exist
2022-03-27 15:57:33.956077: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Operações Matemáticas com Tensores

In [4]:
const_a = tf.constant(5)
const_b = tf.constant(9)

### Soma

In [5]:
total = const_a + const_b
print(total)

tf.Tensor(14, shape=(), dtype=int32)


In [6]:
# Criando os nodes no grado computacional
node1 = tf.constant(5, dtype=tf.int32)
node2 = tf.constant(9, dtype=tf.int32)
node3 = tf.add(node1, node2)

# Executa o grafo
print("\nA soma do node1 com o node2 é: ", node3)


A soma do node1 com o node2 é:  tf.Tensor(14, shape=(), dtype=int32)


### Subtração

In [7]:
rand_a = tf.random.normal([3], 2.0)
rand_b = tf.random.uniform([3], 1.0, 4.0)

In [8]:
print(rand_a)
print(rand_b)

tf.Tensor([1.9018786 3.0005856 0.8956492], shape=(3,), dtype=float32)
tf.Tensor([2.1552129 2.3368363 1.6926208], shape=(3,), dtype=float32)


In [9]:
diff = tf.subtract(rand_a, rand_b)
print("\nA subtração entre os 2 tensores é: ", diff)


A subtração entre os 2 tensores é:  tf.Tensor([-0.25333428  0.6637492  -0.79697156], shape=(3,), dtype=float32)


### Divisão

In [10]:
node1 = tf.constant(21, dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)

In [11]:
# É importante sempre olhar a documentação para localizar a função que você precisa. A cada atualização do software é possível que a função buscada tenha mudado de nome/pacote
div = tf.math.truediv(node1, node2)
print("\nA divisão entre os tensores é: ", div)


A divisão entre os tensores é:  tf.Tensor(3.0, shape=(), dtype=float64)


### Multiplicação

In [12]:
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.], [7.]])

In [13]:
print(tensor_a)
print(tensor_b)

tf.Tensor([[4. 2.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[3.]
 [7.]], shape=(2, 1), dtype=float32)


In [14]:
prod = tf.math.multiply(tensor_a, tensor_b)
print("\nO produto element-wise entre os tensores é: ", prod)


O produto element-wise entre os tensores é:  tf.Tensor(
[[12.  6.]
 [28. 14.]], shape=(2, 2), dtype=float32)


In [15]:
tensor_a = tf.constant([[2, 3], [9, 2], [4, 5]])
tensor_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [16]:
print(tensor_a)
print(tensor_b)

tf.Tensor(
[[2 3]
 [9 2]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[6 4 5]
 [3 7 2]], shape=(2, 3), dtype=int32)


In [17]:
prod = tf.linalg.matmul(tensor_a, tensor_b)
print("\nO produto entre as matrizes é: ", prod)


O produto entre as matrizes é:  tf.Tensor(
[[21 29 16]
 [60 50 49]
 [39 51 30]], shape=(3, 3), dtype=int32)


## Variáveis

In [18]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
# changeable_tensor[0] = 7 -> Erro
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Outras Formas de Preencher Tensores

In [20]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [23]:
rank_2_tensor = tf.constant([[10, 7], [3, 4]])

In [34]:
rank_2_tensor[:2, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 3]], dtype=int32)>

In [28]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>