# Data Science Academy - Python Fundamentos - Capítulo 8

---

In [1]:
import numpy as np
import pandas as pd

## Exercício 1

Crie um array NumPy com 1.000.000 e uma lista com 1.000.000. Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time). 

Qual objeto oferece melhor performance, array NumPy ou lista?

R -> A lista com a multiplicação utilizando um map foi a mais rápida

### np.multiply

In [10]:
array = np.arange(1_000_000)
print(array[:20])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [11]:
%time array = np.multiply(array, 2)

CPU times: user 7.13 ms, sys: 0 ns, total: 7.13 ms
Wall time: 2.73 ms


In [4]:
array = [x for x in range(1_000_000)]
print(array[:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [5]:
## Devagar, converte a lista padrão em ndarray numpy e depois multiplica
%time array = list(np.multiply(array, 2))

CPU times: user 119 ms, sys: 29.7 ms, total: 149 ms
Wall time: 144 ms


### map

In [6]:
array = np.arange(1_000_000)
print(array[:20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
%time array = np.array(map(lambda x: x * 2, array))

CPU times: user 28 µs, sys: 12 µs, total: 40 µs
Wall time: 79.6 µs


In [8]:
array = [x for x in range(1_000_000)]
print(array[:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [9]:
%time array = [map(lambda x: x * 2, array)]

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.58 µs


## Exercício 2

Crie um array de 10 elementos. Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [12]:
array = [x for x in range(10)]
print(f"Array original: {array}")

array[5:9] = [0] * 4
print(f"Array modificado: {array}")

Array original: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Array modificado: [0, 1, 2, 3, 4, 0, 0, 0, 0, 9]


## Exercício 3

Crie um array de 3 dimensões e imprima a dimensão 1 

In [13]:
array = np.zeros((3, 3), dtype=bool)
print(array)
print(array[0])

[[False False False]
 [False False False]
 [False False False]]
[False False False]


## Exercício 4

Crie um array de duas dimensões (matriz). 
- Imprima os elementos da terceira linha da matriz
- Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [14]:
array = np.ndarray((2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
print(f"Matriz:\n{array}")

print("\nTerceira linha da matriz:")
try:
  print(array[2])
except IndexError:
  print("\tErro: A matriz possui apenas duas linhas\n")

print(f"Primeira linha, segunda e terceira colunas: {array[0, 1:]}")
print(f"Segunda linha, segunda e terceira colunas: {array[1, 1:]}")

Matriz:
[[1 2 3]
 [4 5 6]]

Terceira linha da matriz:
	Erro: A matriz possui apenas duas linhas

Primeira linha, segunda e terceira colunas: [2 3]
Segunda linha, segunda e terceira colunas: [5 6]


## Exercício 5

Calcule a transposta da matriz abaixo

In [15]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
## Vide Cap 04.ipynb para outra forma de calcular a transposta
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Exercício 6

Considere os 3 arrays abaixo. Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr

In [17]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [18]:
res = [xarr[i] if c else yarr[i] for i, c in enumerate(cond)]
res

[1.1, 2.2, 1.3, 1.4, 2.5]

## Exercício 7

Crie um array A com 10 elementos e salve o array em disco com a extensão npy. Depois carregue o array do disco no array B

In [19]:
A = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
np.save("ex7.npy", A)

In [20]:
A = np.load("ex7.npy")
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercício 8

Considerando a série abaixo, imprima os valores únicos na série

In [21]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

## Exercício 9

Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.

In [ ]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

# Requisição para página da API não funcionou
import requests
resp = requests.get(url)
resp

# Testando com urllib3 - Também não funcionou
# import urllib3
# http = urllib3.PoolManager()
# r = http.request("GET", url)
# r.status


In [ ]:
# Resposta da DSA
data = resp.json()
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

## Exercício 10

Crie um banco de dados no SQLite, crie uma tabela, insira registros, consulte a tabela e retorne os dados em dataframe do Pandas

In [23]:
# Remove o arquivo com o banco de dados SQLite (caso exista)
import os
os.remove("ex10.db") if os.path.exists("ex10.db") else None

In [24]:
# Cria um banco de dados SQLite
import sqlite3
conn = sqlite3.connect("ex10.db")
cur = conn.cursor()

In [25]:
# Cria uma tabela testes
cur.execute('CREATE TABLE IF NOT EXISTS testes '\
  '(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name TEXT)')

In [26]:
# Insere registros
cur.execute('INSERT INTO testes VALUES (1, "teste 01")')
conn.commit()

cur.execute('INSERT INTO testes VALUES (2, "teste 02")')
conn.commit()

cur.execute('INSERT INTO testes VALUES (3, "teste 03")')
conn.commit()


In [27]:
# Consulta a tabela e retorna os dados em dataframe do Pandas
df = pd.read_sql_query("SELECT * FROM testes", conn)
df = df.set_index("id")
df

name
id          
1   teste 01
2   teste 02
3   teste 03

In [28]:
# Fecha a conexão
cur.close()
conn.close()